export const PORT_VAR={
    PORT:"PORT",
}
export const BD_VARS={
    MONGODB_USER:"MONGODB_USER",
    MONGODB_PASSWORD:"MONGODB_PASSWORD",
    MONGODB_DB:"MONGODB_DB",
    MONGODB_URL:"MONGODB_URL",
};

export const CLOUDINARY_VARS={
    CLOUDINARY_CLOUD_NAME:"CLOUDINARY_CLOUD_NAME",
CLOUDINARY_API_KEY:"CLOUDINARY_API_KEY",
CLOUDINARY_API_SECRET:"CLOUDINARY_API_SECRET",
}
export const AN_HOUR=60*60*1000;
export const ONE_DAY=24*AN_HOUR;