export const PORT_VAR={
    PORT:"PORT",
}
export const BD_VARS={
    MONGODB_USER:"MONGODB_USER",
    MONGODB_PASSWORD:"MONGODB_PASSWORD",
    MONGODB_DB:"MONGODB_DB",
    MONGODB_URL:"MONGODB_URL",
};

export const AN_HOUR=60*60*1000;
export const ONE_DAY=24*AN_HOUR;